packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.45.26
  "@platforma-sdk/ui-vue": ^1.45.26
  "@platforma-sdk/workflow-tengo": ^5.5.17
  "@platforma-sdk/block-tools": ^2.6.18
  "@platforma-sdk/test": ^1.45.27
  "@platforma-sdk/tengo-builder": ^2.3.6
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.1.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
  "@milaboratories/graph-maker": ^1.1.177

  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.21
  "@platforma-open/milaboratories.software-ptabler": "1.12.4"
  "@platforma-open/milaboratories.runenv-python-3": ^1.3.1
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.6.3
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
