packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.40.5
  "@platforma-sdk/ui-vue": ^1.40.5
  "@platforma-sdk/workflow-tengo": ^4.10.0
  "@platforma-sdk/block-tools": ^2.5.69
  "@platforma-sdk/test": ^1.40.5
  "@platforma-sdk/tengo-builder": ^2.1.12
  "@platforma-sdk/package-builder": ^2.16.2
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.134

  '@milaboratories/software-pframes-conv': ^2.2.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.21
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.6.3
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
