packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.42.36
  "@platforma-sdk/ui-vue": ^1.42.36
  "@platforma-sdk/workflow-tengo": ^5.1.1
  "@platforma-sdk/block-tools": ^2.5.92
  "@platforma-sdk/test": ^1.42.41
  "@platforma-sdk/tengo-builder": ^2.1.17
  "@platforma-sdk/package-builder": 3.0.2
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.153

  '@milaboratories/software-pframes-conv': ^2.2.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.21
  "@platforma-open/milaboratories.runenv-python-3": ^1.3.1
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.6.3
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
  "js-yaml": ^4.1.0
