packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.34.0
  "@platforma-sdk/ui-vue": ^1.34.4
  "@platforma-sdk/workflow-tengo": ^4.7.4
  "@platforma-sdk/block-tools": ^2.5.55
  "@platforma-sdk/test": ^1.34.3
  "@platforma-sdk/tengo-builder": ^2.1.10
  "@platforma-sdk/package-builder": ^2.16.1
  "@platforma-sdk/eslint-config": ^1.0.1
  "@milaboratories/graph-maker": ^1.1.125

  '@milaboratories/software-pframes-conv': ^2.1.19
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  
  "vue": ^3.5.12
  "vue-tsc": ^2.1.6
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
